from __future__ import annotations

# Поправки внешних факторов из учебной методики приложения 1.
REFERENCE_TEMPERATURE_C = 15.0
LOW_TEMPERATURE_EFFICIENCY_GAIN_PER_C = 0.003
HIGH_TEMPERATURE_EFFICIENCY_LOSS_PER_C = 0.002

REFERENCE_HUMIDITY_PERCENT = 60.0
HIGH_HUMIDITY_EFFICIENCY_LOSS_PER_PERCENT = 0.0005

WIND_SPEED_EFFECT_PER_MPS = 0.002
MAX_EFFECTIVE_WIND_SPEED_MPS = 8.0

HEAD_WIND_DIRECTION_MIN_DEG = 0.0
HEAD_WIND_DIRECTION_MAX_DEG = 45.0
TAIL_WIND_DIRECTION_MIN_DEG = 180.0
TAIL_WIND_DIRECTION_MAX_DEG = 225.0
HEAD_WIND_FACTOR = 0.99
TAIL_WIND_FACTOR = 1.01
NEUTRAL_WIND_DIRECTION_FACTOR = 1.0

DEFAULT_LOAD_BETA = 0.4

# Собственные нужды.
OWN_NEEDS_HIGH_TEMPERATURE_THRESHOLD_C = 25.0
OWN_NEEDS_LOW_TEMPERATURE_THRESHOLD_C = 0.0
OWN_NEEDS_HIGH_TEMPERATURE_INCREASE_PER_C = 0.005
OWN_NEEDS_LOW_TEMPERATURE_INCREASE_PER_C = 0.003

# Удельный расход топлива. Коэффициент 123 сохранен из исходной учебной модели.
FUEL_CONSUMPTION_COEFFICIENT = 123.0

# Учебная модель разрежения в конденсаторе.
OPTIMAL_CONDENSER_VACUUM_KPA = 88.0
MIN_CONDENSER_VACUUM_FACTOR = 0.94
CONDENSER_VACUUM_QUADRATIC_LOSS = 0.00035


__all__ = ['REFERENCE_TEMPERATURE_C', 'LOW_TEMPERATURE_EFFICIENCY_GAIN_PER_C', 'HIGH_TEMPERATURE_EFFICIENCY_LOSS_PER_C', 'REFERENCE_HUMIDITY_PERCENT', 'HIGH_HUMIDITY_EFFICIENCY_LOSS_PER_PERCENT', 'WIND_SPEED_EFFECT_PER_MPS', 'MAX_EFFECTIVE_WIND_SPEED_MPS', 'HEAD_WIND_DIRECTION_MIN_DEG', 'HEAD_WIND_DIRECTION_MAX_DEG', 'TAIL_WIND_DIRECTION_MIN_DEG', 'TAIL_WIND_DIRECTION_MAX_DEG', 'HEAD_WIND_FACTOR', 'TAIL_WIND_FACTOR', 'NEUTRAL_WIND_DIRECTION_FACTOR', 'DEFAULT_LOAD_BETA', 'OWN_NEEDS_HIGH_TEMPERATURE_THRESHOLD_C', 'OWN_NEEDS_LOW_TEMPERATURE_THRESHOLD_C', 'OWN_NEEDS_HIGH_TEMPERATURE_INCREASE_PER_C', 'OWN_NEEDS_LOW_TEMPERATURE_INCREASE_PER_C', 'FUEL_CONSUMPTION_COEFFICIENT', 'OPTIMAL_CONDENSER_VACUUM_KPA', 'MIN_CONDENSER_VACUUM_FACTOR', 'CONDENSER_VACUUM_QUADRATIC_LOSS']
